# This file is machine-generated - editing it directly is not advised

manifest_format = "2.0"

[[deps.ActualImport]]
path = "/home/kevin/Repos/actual-import"
uuid = "36286069-a8d2-477d-b871-70fac298da0d"

    [deps.ActualImport.apps.actualimport]
    julia_command = "/home/kevin/Dotfiles/julia/.julia/juliaup/julia-1.12.0-beta2+0.x64.linux.gnu/bin/julia"
    julia_version = "1.12.0-beta2"
