# preload = ~/.config/backgrounds/shaded.png
# preload = ~/.config/backgrounds/Tsunami_by_hokusai_19th_century.jpg
# preload = ~/.config/backgrounds/cherry-blossoms.jpg
# preload = ~/.config/backgrounds/river-boat.jpg

wallpaper {
  monitor = DP-13
  path = ~/.config/backgrounds/cherry-blossoms.jpg
}

wallpaper {
  monitor = DP-15
  path = ~/.config/backgrounds/cherry-blossoms.jpg
}

wallpaper {
  monitor =
  path = ~/.config/backgrounds/Tsunami_by_hokusai_19th_century.jpg
}

