set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set -g set-clipboard on

# for kitty terminal images
set -g allow-passthrough all
set -g update-environment "TERM_PROGRAM"

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind r source-file ~/.tmux.conf \; display "Config reloaded"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

bind p copy-mode

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Maximize pane
bind -n M-m resize-pane -Z

# Swap panes with Ctrl+Shift+hjkl
set -g extended-keys on
bind -n C-M-h swap-pane -t '{left-of}'
bind -n C-M-j swap-pane -t '{down-of}'
bind -n C-M-k swap-pane -t '{up-of}'
bind -n C-M-l swap-pane -t '{right-of}'

# Resize panes with Alt+hjkl (pass through to nvim if active)
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind -n M-h if-shell "$is_vim" 'send-keys M-h' 'resize-pane -L 5'
bind -n M-j if-shell "$is_vim" 'send-keys M-j' 'resize-pane -D 5'
bind -n M-k if-shell "$is_vim" 'send-keys M-k' 'resize-pane -U 5'
bind -n M-l if-shell "$is_vim" 'send-keys M-l' 'resize-pane -R 5'


# Vim style pane selection
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @catppuccin_flavour 'mocha'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'

# Local vs remote indicator (checks if SSH_TTY is in tmux's environment)
#set -ag status-right " #(tmux show-environment SSH_TTY 2>/dev/null | grep -q '=' && echo ' remote ('"$(hostname -s)"')' || echo ' local')"

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"
bind n new-window -c "#{pane_current_path}"
